/** Shared light-theme classes for TIS Integrator (readable on dark admin shell). */

export const tis = {
  shell: "rounded-xl border border-slate-200 bg-gradient-to-b from-slate-50 via-white to-slate-50 text-slate-900 shadow-sm",
  banner:
    "rounded-lg border border-indigo-200 bg-gradient-to-r from-indigo-50 via-sky-50 to-indigo-50 px-4 py-3",
  bannerTitle: "text-sm font-semibold text-slate-900",
  bannerDesc: "text-xs text-slate-600",
  h2: "text-lg font-semibold text-slate-900",
  subtitle: "text-sm text-slate-600",
  card: "border-slate-200 bg-white shadow-sm",
  cardTitle: "text-base font-semibold text-slate-900",
  cardDesc: "text-slate-600",
  input: "border-slate-300 bg-white text-slate-900 placeholder:text-slate-400",
  select: "border-slate-300 bg-white text-slate-900",
  infoBox: "rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600",
  code: "font-mono text-indigo-700",
  tabsList: "flex h-auto flex-wrap gap-1 border border-slate-200 bg-slate-100 p-1",
  tabsTrigger:
    "gap-2 text-slate-700 data-[state=active]:bg-indigo-600 data-[state=active]:text-white data-[state=active]:shadow-sm",
  tableWrap: "rounded-md border border-slate-200 bg-white",
  tableHead: "text-slate-700 font-semibold",
  tableRow: "border-slate-100 hover:bg-slate-50",
  tableCell: "text-slate-800",
  tableCellMuted: "text-slate-500",
  tableCellMono: "font-mono text-xs text-slate-700",
  statValue: "text-2xl font-semibold text-slate-900",
  statLabel: "text-xs text-slate-600",
  checklistItem: "border-slate-200 bg-white hover:bg-slate-50 shadow-sm",
  checklistCategory: "text-sm font-semibold text-slate-800",
  checklistLabel: "text-sm font-medium text-slate-900",
  checklistDesc: "text-xs text-slate-600",
  initCard: "rounded-lg border border-sky-200 bg-sky-50/80 p-4",
  initTitle: "text-sm font-semibold text-slate-900",
  initDesc: "text-xs text-slate-600 mt-1",
  timeline: "rounded-md border border-slate-200 bg-slate-50 p-3",
  timelineTitle: "text-xs font-semibold text-slate-700",
  pre: "max-h-64 overflow-auto rounded-md border border-slate-200 bg-slate-50 p-3 text-[11px] text-slate-800",
} as const;
