/**
 * ╔══════════════════════════════════════════════════════════════════════════════════════╗
 * ║                                                                                      ║
 * ║   🔌 SUPABASE CLIENT - DATABASE CONNECTION                                          ║
 * ║                                                                                      ║
 * ║   ⚠️  SECURITY CRITICAL - DO NOT MODIFY  ⚠️                                         ║
 * ║                                                                                      ║
 * ║   SECURITY AUDIT: December 24, 2025                                                  ║
 * ║   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ║
 * ║                                                                                      ║
 * ║   SECURITY CONFIGURATION:                                                            ║
 * ║   ┌─────────────────────────────────────────────────────────────────────────────┐   ║
 * ║   │  1. Uses ANON key (public, safe for client-side)                           │   ║
 * ║   │  2. PKCE flow for secure OAuth                                              │   ║
 * ║   │  3. Auto token refresh enabled                                              │   ║
 * ║   │  4. Session storage: localStorage (default) or sessionStorage (optional)    │   ║
 * ║   │  5. RLS policies enforce data access on server-side                         │   ║
 * ║   └─────────────────────────────────────────────────────────────────────────────┘   ║
 * ║                                                                                      ║
 * ║   IMPORTANT: The ANON key is safe to expose - security is enforced by RLS.         ║
 * ║   Never expose the SERVICE_ROLE key in client-side code!                           ║
 * ║                                                                                      ║
 * ╚══════════════════════════════════════════════════════════════════════════════════════╝
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer VITE_SUPABASE_* for rotation and multi-environment deploys. Dev fallback matches prior embedded defaults.
const LEGACY_DEV_URL = 'https://wuuyjjpgzgeimiptuuws.supabase.co';
const LEGACY_DEV_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dXlqanBnemdlaW1pcHR1dXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTY4NjMsImV4cCI6MjA3MTE3Mjg2M30.7r2Fd-perL2cC7IR4R06GLWrY9xKkxa0ZDnmmSCWgTo';

function resolveSupabaseUrl(): string {
  const v = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
  if (v) return v.replace(/\/+$/, '');
  if (import.meta.env.DEV) {
    console.warn('[supabase] VITE_SUPABASE_URL unset; using legacy dev project URL');
    return LEGACY_DEV_URL;
  }
  throw new Error(
    'Missing VITE_SUPABASE_URL. Set it in your environment (e.g. Vercel project env) for production builds.'
  );
}

function resolveSupabaseAnonKey(): string {
  const v = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();
  if (v) return v;
  if (import.meta.env.DEV) {
    console.warn('[supabase] VITE_SUPABASE_ANON_KEY unset; using legacy dev anon key');
    return LEGACY_DEV_ANON_KEY;
  }
  throw new Error(
    'Missing VITE_SUPABASE_ANON_KEY. Set it in your environment for production builds — use the anon key, never service_role.'
  );
}

export const SUPABASE_URL = resolveSupabaseUrl();
export const SUPABASE_ANON_KEY = resolveSupabaseAnonKey();

// Alias for backward compatibility
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_ANON_KEY;

/**
 * Session storage:
 * - Production default: sessionStorage (smaller XSS theft window; session ends when the tab/window closes).
 * - Persistent login: set VITE_SUPABASE_AUTH_STORAGE=local
 * - Force session: set VITE_SUPABASE_AUTH_STORAGE=session
 */
function resolveAuthStorage(): Storage {
  const explicit = (import.meta.env.VITE_SUPABASE_AUTH_STORAGE as string | undefined)?.trim().toLowerCase();
  if (explicit === 'session') return sessionStorage;
  if (explicit === 'local') return localStorage;
  return import.meta.env.PROD ? sessionStorage : localStorage;
}

const authStorage = resolveAuthStorage();

/** True when PostgREST / Supabase-js returned an abort (global fetch timeout, navigation, or auth churn). */
export function isAbortLikeSupabaseError(err: unknown): boolean {
  if (err == null || typeof err !== 'object') return false;
  const e = err as { name?: string; message?: string };
  return e.name === 'AbortError' || /aborted|signal is aborted/i.test(String(e.message || ''));
}

/** Upper bound for PostgREST / RPC calls (RLS-heavy lists can exceed 15s). Override with VITE_SUPABASE_FETCH_TIMEOUT_MS. */
function resolveSupabaseGlobalFetchTimeoutMs(): number {
  const raw = (import.meta.env.VITE_SUPABASE_FETCH_TIMEOUT_MS as string | undefined)?.trim();
  if (raw) {
    const n = parseInt(raw, 10);
    if (Number.isFinite(n) && n >= 5_000) return Math.min(n, 300_000);
  }
  return 90_000;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  // Bounded fetch time + honor Supabase's own AbortSignal (session refresh / dedup) instead of replacing it.
  global: {
    fetch: (url, options?: RequestInit) => {
      const timeoutMs = resolveSupabaseGlobalFetchTimeoutMs();
      const parentSignal = options?.signal;
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

      const onParentAbort = () => {
        clearTimeout(timeoutId);
        controller.abort();
      };

      if (parentSignal) {
        if (parentSignal.aborted) {
          clearTimeout(timeoutId);
          const reason = parentSignal.reason;
          return Promise.reject(
            reason instanceof Error ? reason : new DOMException('The operation was aborted', 'AbortError')
          );
        }
        parentSignal.addEventListener('abort', onParentAbort, { once: true });
      }

      return fetch(url, {
        ...options,
        signal: controller.signal,
      }).finally(() => {
        clearTimeout(timeoutId);
        if (parentSignal) parentSignal.removeEventListener('abort', onParentAbort);
      });
    },
  },
  // Disable realtime to reduce connections
  realtime: {
    params: {
      eventsPerSecond: 1
    }
  }
});

// Helper function for direct fetch API calls (bypasses Supabase client)
export const supabaseFetch = async (
  endpoint: string, 
  options: { method?: string; body?: any; token?: string } = {}
) => {
  const { method = 'GET', body, token } = options;
  
  const headers: Record<string, string> = {
    'apikey': SUPABASE_ANON_KEY,
    'Content-Type': 'application/json',
  };
  
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15000);
  
  try {
    const response = await fetch(`${SUPABASE_URL}/rest/v1/${endpoint}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
      signal: controller.signal
    });
    
    clearTimeout(timeoutId);
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    
    return await response.json();
  } catch (err: any) {
    clearTimeout(timeoutId);
    if (err.name === 'AbortError') {
      throw new Error('Request timeout');
    }
    throw err;
  }
};