/**
 * ╔══════════════════════════════════════════════════════════════════════════════════════╗
 * ║                                                                                      ║
 * ║   🔌 SUPABASE CLIENT - DATABASE CONNECTION                                          ║
 * ║                                                                                      ║
 * ║   ⚠️  SECURITY CRITICAL - DO NOT MODIFY  ⚠️                                         ║
 * ║                                                                                      ║
 * ║   SECURITY AUDIT: December 24, 2025                                                  ║
 * ║   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ║
 * ║                                                                                      ║
 * ║   SECURITY CONFIGURATION:                                                            ║
 * ║   ┌─────────────────────────────────────────────────────────────────────────────┐   ║
 * ║   │  1. Uses ANON key (public, safe for client-side)                           │   ║
 * ║   │  2. PKCE flow for secure OAuth                                              │   ║
 * ║   │  3. Auto token refresh enabled                                              │   ║
 * ║   │  4. Session persisted in localStorage                                       │   ║
 * ║   │  5. RLS policies enforce data access on server-side                         │   ║
 * ║   └─────────────────────────────────────────────────────────────────────────────┘   ║
 * ║                                                                                      ║
 * ║   IMPORTANT: The ANON key is safe to expose - security is enforced by RLS.         ║
 * ║   Never expose the SERVICE_ROLE key in client-side code!                           ║
 * ║                                                                                      ║
 * ╚══════════════════════════════════════════════════════════════════════════════════════╝
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Centralized Supabase configuration - import these instead of hardcoding
export const SUPABASE_URL = "https://wuuyjjpgzgeimiptuuws.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1dXlqanBnemdlaW1pcHR1dXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTY4NjMsImV4cCI6MjA3MTE3Mjg2M30.7r2Fd-perL2cC7IR4R06GLWrY9xKkxa0ZDnmmSCWgTo";

// Alias for backward compatibility
const SUPABASE_PUBLISHABLE_KEY = SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});